packaging_format = 2

id = "kakeibo"
name = "Kakeibo"
description.en = "Family Financial Mindfulness App"
description.fr = "Application de pleine conscience financière familiale"

version = "0.1.0~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://github.com/yourusername/kakeibo-fiber"
code = "https://github.com/yourusername/kakeibo-fiber"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    # This allows using ProtectHome=true in systemd unit.
    dir = "/var/run/__APP__"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 4000

    #[resources.apt]
    #packages = ["sqlite3"]

