#!/bin/bash
#
# TODO: finish this script

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKING UP SYSTEMD SERVICE
#=================================================

ynh_print_info --message="Backing up systemd service..."
ynh_backup --src_path="/etc/systemd/system/$app.service"

#=================================================
# BACKING UP NGINX CONFIGURATION
#=================================================

ynh_print_info --message="Backing up nginx configuration..."
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKING UP DATA DIRECTORY
#=================================================

ynh_print_info --message="Backing up data directory..."
ynh_backup --src_path="$data_dir"

#=================================================
# BACKING UP INSTALL DIRECTORY
#=================================================

ynh_print_info --message="Backing up install directory..."
ynh_backup --src_path="$install_dir"

