#!/bin/bash
#
# TODO: finish this script

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORING DATA DIRECTORY
#=================================================

ynh_script_progression --message="Restoring data directory..."
ynh_restore_file --origin_path="$data_dir"
chown -R $app:$app "$data_dir"
chmod 750 "$data_dir"
chmod 640 "$data_dir/*"

#=================================================
# RESTORING INSTALL DIRECTORY
#=================================================

ynh_script_progression --message="Restoring install directory..."
ynh_restore_file --origin_path="$install_dir"
chown -R $app:$app "$install_dir"
chmod +x "$install_dir/kakeibo"

#=================================================
# RESTORING SYSTEMD SERVICE
#=================================================

ynh_script_progression --message="Restoring systemd service..."
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet
systemctl daemon-reload

#=================================================
# RESTORING NGINX CONFIGURATION
#=================================================

ynh_script_progression --message="Restoring nginx configuration..."
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# RESTORING LOGGING
#=================================================
ynh_script_progression --message="Setting up logging..."
mkdir -p /var/log/$app
chown -R $app:$app /var/log/$app
chmod 750 /var/log/$app
ynh_restore_file --origin_path="/var/log/kakeibo/kakeibo.log"

#=================================================
# STARTING SERVICE
#=================================================

ynh_script_progression --message="Starting Kakeibo..."
ynh_systemd_action --service_name=$app --action="start" --line_match="Starting server on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed" --last
